# Generated by Django 5.0.1 on 2024-08-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('loan_type', models.CharField(choices=[('Personal', 'Personal'), ('Institutional', 'Institutional')], max_length=50)),
                ('govt_id_type', models.CharField(max_length=100)),
                ('govt_id_number', models.CharField(max_length=100)),
                ('govt_id_upload', models.ImageField(upload_to='govt_ids/')),
                ('photo_capture', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('home_coordinates', models.CharField(max_length=100)),
                ('collateral_type', models.CharField(max_length=50)),
                ('collateral_coordinates', models.CharField(blank=True, max_length=100, null=True)),
                ('collateral_details', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
